# Generated by Django 2.1.3 on 2019-02-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coststatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=10, verbose_name='产品编号')),
                ('SubscriptionType', models.CharField(max_length=30, verbose_name='计费类型')),
                ('PaymentAmount', models.FloatField(default=0.0, verbose_name='费用')),
                ('BillingCycle', models.DateField(verbose_name='账单期')),
            ],
        ),
    ]
