# Generated by Django 2.0.7 on 2018-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=256)),
                ('group_desc', models.CharField(max_length=256)),
            ],
        ),
    ]
