# Generated by Django 2.1.3 on 2019-03-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mygroup',
            name='permission_list',
        ),
        migrations.DeleteModel(
            name='MyGroup',
        ),
    ]
