# Generated by Django 2.1.3 on 2019-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
