# Generated by Django 2.1.3 on 2019-03-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='mygroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group'),
        ),
    ]
