# Generated by Django 2.0.7 on 2018-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='', max_length=256)),
                ('ipaddr', models.CharField(max_length=256)),
                ('sshport', models.IntegerField(default=22)),
                ('remote_user', models.CharField(max_length=40)),
                ('host_desc', models.CharField(max_length=256)),
            ],
        ),
    ]
