# Generated by Django 2.0.7 on 2018-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20180723_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
