# Generated by Django 2.0.7 on 2018-07-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20180723_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
