# Generated by Django 2.1.3 on 2019-02-25 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memory_used', models.FloatField(default=0, verbose_name='内存MB')),
                ('cpu_used', models.FloatField(default=0, verbose_name='统计当前cpu使用率')),
                ('disk_used', models.FloatField(default=0, verbose_name='统计磁盘使用情况')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('lists', models.CharField(choices=[('', '------'), ('title1', '标题1'), ('title2', '标题2'), ('title3', '标题3')], default='------', max_length=50)),
                ('host', models.ManyToManyField(blank=True, to='monitor.Blog', verbose_name='标题')),
            ],
            options={
                'verbose_name': '系统资源监控',
                'db_table': 'resource_monitor',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
