# Generated by Django 2.0.7 on 2018-08-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitor',
            table='Monitor',
        ),
    ]
