# Generated by Django 2.0.7 on 2018-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='disk_spare',
            field=models.FloatField(default=0, verbose_name='剩余硬盘MB'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='memory_spare',
            field=models.FloatField(default=0, verbose_name='剩余内存MB'),
        ),
    ]
