# Generated by Django 2.0.7 on 2018-08-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_auto_20180816_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='cpu_used',
        ),
        migrations.AddField(
            model_name='monitor',
            name='cpu_load_10m',
            field=models.FloatField(default=0, verbose_name='统计当前平均10分钟负载'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='cpu_load_15m',
            field=models.FloatField(default=0, verbose_name='统计当前平均15分钟负载'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='cpu_load_5m',
            field=models.FloatField(default=0, verbose_name='统计当前平均5分钟负载'),
        ),
    ]
