# Generated by Django 2.0.7 on 2018-08-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180815_0639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitor',
            table='monitor',
        ),
    ]
