# Generated by Django 2.0.7 on 2018-08-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_auto_20180816_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'permissions': (('open_monitor', 'can open monitor to query'), ('reply_monitor', 'can reply monitor'), ('close_monitor', 'close monitor'))},
        ),
    ]
