# Generated by Django 2.0.7 on 2018-08-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180815_0641'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitor',
            table='Monitor',
        ),
    ]
