# Generated by Django 2.0.7 on 2018-08-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180815_0644'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitor',
            table='resource_monitor',
        ),
    ]
