# Generated by Django 2.0.7 on 2018-07-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20180723_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
