# Generated by Django 2.0.7 on 2018-07-25 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_host_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='writeiops_avg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='写操作iops平均值'),
        ),
        migrations.AddField(
            model_name='metric',
            name='writeiops_max',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='写操作iops峰值'),
        ),
    ]
