# Generated by Django 2.1.3 on 2019-02-13 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildhistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobname', models.CharField(max_length=50, verbose_name='job 名称')),
                ('buildid', models.IntegerField(default='', verbose_name='Build Id')),
                ('viewname', models.CharField(max_length=50, verbose_name='试图名称')),
                ('parameters', models.CharField(default='', max_length=200, verbose_name='构建参数')),
                ('starttime', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始构建时间')),
                ('buildtime', models.FloatField(default=0, max_length=20, verbose_name='构建时间')),
                ('buildresult', models.CharField(choices=[('success', 1), ('failure', 0)], max_length=20, verbose_name='构建结果')),
            ],
            options={
                'db_table': 'Buildhistory',
            },
        ),
    ]
