# Generated by Django 2.0.7 on 2018-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('parent_id', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=128)),
                ('sort', models.IntegerField(default=0)),
                ('span_id', models.IntegerField()),
                ('create_time', models.DateTimeField(default='2018-07-23 07:27:06')),
            ],
        ),
    ]
