# Generated by Django 2.1.3 on 2019-02-13 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Menu name')),
                ('parent_id', models.IntegerField(default=0, verbose_name='Parent menu id')),
                ('url', models.CharField(max_length=128, verbose_name='link url address')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
    ]
