# Generated by Django 2.0.7 on 2018-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180828_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sort',
        ),
    ]
