# Generated by Django 2.0.7 on 2018-09-13 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Menu name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='Parent menu id'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=128, verbose_name='link url address'),
        ),
    ]
